### ISSUE TITLE
Use the sync type flag in SPWF04SA

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Drivers#10]
https://community.st.com/thread/45686-how-to-use-the-sockdw-command-correctly-over-spi-on-spwf04sa#comment-177418

Apparently the WIND field has meaning in responses as well. We could just skip anything 0xFE to simplify the response reading in the higher level commands. Especially since things like cert loading may or may not happen.

Y == 0x03 appears to mean payload, not AT-S.ERROR.

Moved from ghi-electronics/TinyCLR-Libraries#180

**Comment by Arke64** [comment]
https://community.st.com/s/question/0D50X00009XkXCySAN/how-to-use-the-sockdw-command-correctly-over-spi-on-spwf04sa updated link

**Comment by Arke64** [comment]
So for `KindOfEvent` == 0x03, payload data, the manual doesn't assign any meaning to the `Indication Number` field. According to the above post and our tests, it does appear to have a meaning.

0x00: AT-S.OK without payload
0x03: AT-S.OK with payload
0xFF: AT-S.x not maskable
0xFE: AT-S.x maskable

**Comment by Arke64** [comment]
We could also use the `Y == Z` case to signal errors back to the command and its reader, poisoning it in the same way mentioned in #21, not just raising an error received event.

**Comment by Arke64** [comment]
Update #38 when done

**Comment by Palomino34** [comment]
No longer support this wifi.
