### ISSUE TITLE
Add SPI support to the Solomon Systech SSD1306 Driver

### ISSUE THREAD

**Issue by Experiment-626** [ghi-electronics/TinyCLR-Drivers#11]
The Solomon Systech Driver was added with I2C support, primarily for the BrainPad driver. The SPI interface would need to be added to allow the this driver to remain independent.

**Comment by Arke64** [comment]
[SPI.zip](https://github.com/ghi-electronics/TinyCLR-Drivers/files/2397239/SPI.zip)
