### ISSUE TITLE
HiLetgo.ILI9341 Driver Throwing Error

### ISSUE THREAD

**Issue by kirklynk** [ghi-electronics/TinyCLR-Drivers#125]
Currently, the GHIElectronics.TinyCLR.Drivers.HiLetgo.ILI9341 driver is throwing a "Null Reference" exception whenever the Reset method is called. This is due to the fact that the reset pin could be null.

The fix, add nullable check on reset pin references in reset method:
this.reset?.Write(GpioPinValue.Low);
Thread.Sleep(50);

this.reset?.Write(GpioPinValue.High);
Thread.Sleep(200);

**Comment by Palomino34** [comment]
Fixed. Thanks
