### ISSUE TITLE
APA102C Drivers - Number of Leds and Stop Frame

### ISSUE THREAD

**Issue by bauland** [ghi-electronics/TinyCLR-Drivers#16]
In APA102C driver, when number of LED is for example 15, the stop frame is too large and is interpreated as white leds.

```           
SpiController _spiCtl = SpiController.FromName(FEZ.SpiBus.Spi1);
            var _spi = _spiCtl.GetDevice(APA102CController.GetConnectionSettings());
            int LED = 15;
            APA102CController ctl = new APA102CController(_spi, LED);
            for (int i = 0; i < LED; i++)
            {
                ctl.Set(i,Color.Black);
            }
            // ctl.Set(5,Color.Purple);
            ctl.Flush();

            for (int i = 0; i < LED; i++)
            {
                ctl.Set(i, Color.Blue, 0b0001_1111 * i / LED);
            }
            ctl.Flush();

            while (true)
            {
                Thread.Sleep(20);
            }
```

**Comment by Arke64** [comment]
So it doesn't appear to be a bug on our end. The stop frame has the exact same bit-format as a pure white frame. So when you send ten LED frames, those all show up fine, then the LED after the last shows up as pure white (the stop frame). Omitting the stop frame causes other issues and is not indicated as optional anyway in the datasheet. If anything, it's a bug in the LED hardware itself where the stop frame and pure white have the same format.

The correct way to proceed here is the pass the driver the number of LEDs that are actually on the strip, not just how much you want to use. You can keep those unused LEDs set to black and only change the ones you need.
