### ISSUE TITLE
V2.1.0 Preview 4: Command 'Winc15x0Interface.GetFirmwareVersion();' before initialization crashes and makes board unresponsive

### ISSUE THREAD

**Issue by RoSchmi** [ghi-electronics/TinyCLR-Drivers#163]
I'm working with a FEZ Feather TinyCLR V2.1.0 Preview 4.
Mistakenly I used the command 'Winc15x0Interface.GetFirmwareVersion();' before the module was initialized. This crashes application and makes the board unresponsive over USB. Firmware had to be erased in LDR mode and firmware had to be updated.
After initialization of the WiFi module the command worked as expected.
Not a big thing but should perhaps be handled more gracefully.

**Comment by Palomino34** [comment]
Just tried it. Higher than Preview4, and could not reproduce.
Below is code and output:

```cs
var version = Winc15x0Interface.GetFirmwareVersion();

Debug.WriteLine("version : " + version);

networkController.Enable();
```

```
version : 19.5.4.15567
Mac: 70:b3:d5:fa:c0:0f
ip address :192.168.86.37
subnetmask :255.255.255.0
gate way :192.168.86.1
dns[0] :75.75.75.75
dns[1] :75.75.75.76
Phy staus True
```

This is tested on rc1-internal. Not on preview4.

**Comment by RoSchmi** [comment]
Hi, I think you misunderstood my concern. The command only crashes the application and makes the board unresponsive over USB when the command is issued **before** the WiFi module is initialzed. It is clear that it can not work before 'talking to the board' is established. However execution of the command should only be performed by the firmware after the SPI connection is successfully established. After successful initialization the command works, but this was not my concern.
