### ISSUE TITLE
SPWF04 shows ConfigurationFailure on startup

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Drivers#17]
We've seen it a lot on our end, also customers: https://forums.ghielectronics.com/t/wind-configurationfailure-10-for-fez-spwf04sa-wi-fi-module/

**Comment by Palomino34** [comment]
because we force to SPI mode while configuration is UART.

Set console_enabled = 0 for default SPI then no ConfigurationFailure shown.
