### ISSUE TITLE
Add driver for 7x10 dot matrix LED click

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Drivers#20]

**Comment by Arke64** [comment]
From @Experiment-626 : "This module does not use the simple 74HC595 shift register (https://download.mikroe.com/documents/datasheets/74HC595.pdf). It uses a CMOS Counter/Divider CD4017 (https://download.mikroe.com/documents/datasheets/CD4017.pdf) in conjunction with the shift register."

**Comment by Experiment-626** [comment]
Drivers were made for the 74HC595 and CD4017 chips. Please see PR https://github.com/ghi-electronics/TinyCLR-Drivers/pull/22 and https://github.com/ghi-electronics/TinyCLR-Drivers/pull/23. Test code can be found here: https://gist.github.com/Experiment-626/8690559eac472be5097dc29a7cb15ff3.
