### ISSUE TITLE
Add timeout to SPWF04Sx

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Drivers#21]
Currently the driver can block inside its semaphore impl. It does pass a timeout to the underlying `ManualResetEvent.WaitOne` but it's done inside an infinite loop. Instead, pass a timeout to the semaphore `WaitOne`. We'll want to expose this further up the chain as well. Needs some thought on how we handle timeouts, particularly for multi-command calls like `Join`.

**Comment by Arke64** [comment]
See #38 

We do want to pass the timeout to the semaphore so it returns. The entire read call should return the default of its type. Commands that call read multiple times will just carry on calling the next read, so anytime we error out in a command, we should poison future calls to read on the same command so they return immediately. We may have to adjust a few of the callsites to ensure they can operate on the default for the type, making sure to finalize the command and return some sort of error to the user.

Alternatively, timeout just throws a timeout exception and we wrap all read calls in a try {} finally {} block. Finally is needed so we can call finalize command and properly dispose of it so we can issue new commands and recover.

**Comment by Palomino34** [comment]
No longer support this wifi.
