### ISSUE TITLE
Figure out what to do about python pin on SPWF04Sx

### ISSUE THREAD

**Issue by Arke64** [ghi-electronics/TinyCLR-Drivers#28]
Since the firmwares now default pins to input-pullup, the Wi-Fi module is put into python mode by default. We don't want to change the firmware for this one pin because it's very specific and not every use of the firmware will have Wi-Fi. Adding a constructor parameter for the pin is probably the best way to go, perhaps call it mode. Will need to add to the pins library as appropriate. For now the pin can manually be set to low if needed.

**Comment by Palomino34** [comment]
No longer support this wifi.
